version: "3.9"

services:
  # wireguard:
  #   image: linuxserver/wireguard
  #   container_name: wireguard
  #   restart: unless-stopped
  #   networks:
  #     - vpn
  #   volumes:
  #     - './wireguard:/config'
  #     - '/lib/modules:/lib/modules:ro'
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  bankapp:
    # depends_on:
    #   - wireguard
    build:
      context: bankapp
    ports:
      - "5002:22"
      - "5000:5000"
    # network_mode: service:wireguard
  # dns:
  #   build:
  #     context: dns
  #   restart: on-failure
  #   ports:
  #     - "5001:53"
  # shadow-daemon
  db:
    image: zecure/shadowd_database:12.4
    restart: always
    volumes:
      - "${SHADOWD_DB_LOCATION}:/var/lib/postgresql/data"
    env_file:
      - "${SHADOWD_ENV_DB_LOCATION}"

  web:
    image: zecure/shadowd_ui:2
    restart: always
    ports:
      - 127.0.0.1:8080:80
    links:
      - db
    depends_on:
      - db
    environment:
      - "SHADOWD_DB_HOST=db"
    env_file:
      - "${SHADOWD_ENV_DB_LOCATION}"

  shadowd:
    container_name: shadowdserver
    image: zecure/shadowd:2
    restart: always
    expose:
      - "9115"
    links:
      - db
    depends_on:
      - db
    environment:
      - "SHADOWD_DB_HOST=db"
    env_file:
      - "${SHADOWD_ENV_DB_LOCATION}"